version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    deploy:
      mode: global
      endpoint_mode: dnsrr
    command: -config.file=/loki-config.yaml
    networks:
      - loki
    configs:
      - loki-config.yaml
    depends_on:
      - minio
      - etcd-1
      - etcd-2
      - etcd-3
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    depends_on:
      - minio
      - etcd-1
      - etcd-2
      - etcd-3

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - loki
    command: server ~ --address ':9000' --console-address ':9001'

  createbuckets:
    deploy:
      restart_policy:
        condition: none
    image: minio/mc
    networks:
      - loki
    depends_on:
      - minio
      - etcd-1
      - etcd-2
      - etcd-3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/loki;
      /usr/bin/mc mb myminio/loki;
      exit 0;
      "
  etcd-1:
      image: quay.io/coreos/etcd:v3.5.3
      entrypoint: /usr/local/bin/etcd
      command:
          - '--name=etcd-1'
          - '--initial-advertise-peer-urls=http://etcd-1:2380'
          - '--listen-peer-urls=http://0.0.0.0:2380'
          - '--listen-client-urls=http://0.0.0.0:2379'
          - '--advertise-client-urls=http://etcd-1:2379'
          - '--heartbeat-interval=250'
          - '--election-timeout=1250'
          - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
          - '--initial-cluster-state=new'
          - '--initial-cluster-token=mys3cr3ttok3n'
      volumes:
        - etcd1:/etcd_data
      networks:
        - loki
  etcd-2:
      image: quay.io/coreos/etcd:v3.5.3
      entrypoint: /usr/local/bin/etcd
      command:
          - '--name=etcd-2'
          - '--initial-advertise-peer-urls=http://etcd-2:2380'
          - '--listen-peer-urls=http://0.0.0.0:2380'
          - '--listen-client-urls=http://0.0.0.0:2379'
          - '--advertise-client-urls=http://etcd-2:2379'
          - '--heartbeat-interval=250'
          - '--election-timeout=1250'
          - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
          - '--initial-cluster-state=new'
          - '--initial-cluster-token=mys3cr3ttok3n'
      volumes:
        - etcd2:/etcd_data
      networks:
        - loki

  etcd-3:
      image: quay.io/coreos/etcd:v3.5.3
      entrypoint: /usr/local/bin/etcd
      command:
          - '--name=etcd-3'
          - '--initial-advertise-peer-urls=http://etcd-3:2380'
          - '--listen-peer-urls=http://0.0.0.0:2380'
          - '--listen-client-urls=http://0.0.0.0:2379'
          - '--advertise-client-urls=http://etcd-3:2379'
          - '--heartbeat-interval=250'
          - '--election-timeout=1250'
          - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
          - '--initial-cluster-state=new'
          - '--initial-cluster-token=mys3cr3ttok3n'
      volumes:
        - etcd3:/etcd_data
      networks:
        - loki
volumes:
    etcd1:
    etcd2:
    etcd3:
configs:
  loki-config.yaml:
    file: ./config/loki.yaml
networks:
  loki:
    attachable: true
